services:
  springboot-app:
    container_name: springboot-app
    ports:
      - "50001:1212"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env

  db:
    container_name: mysql-db
    ports:
      - "50000:3306"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: