services:
  springboot-app:
    container_name: springboot-app
    ports:
      - "50001:1212"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/user_notes_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    env_file:
      - .env

  db:
    container_name: mysql-db
    ports:
      - "50000:3306"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_notes_db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: